apiVersion: v1
kind: Service
metadata:
  name: user-agent-info
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: my-flask-app
  replicas: 4
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app
          image: my-flask-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
